const gunung = [
    {
        "id": "1",
        "nama": "Seulawah Agam",
        "bentuk": "Stratovulkan",
        "tinggi": "1810 Meter",
        "letusan_terakhir": "1839",
        "geolokasi": "5.448°N 95.658°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/seulawah-agam.jpg"
    },
    {
        "id": "2",
        "nama": "Peuet Sagoe",
        "bentuk": "Kompleks",
        "tinggi": "2801 meter",
        "letusan_terakhir": "25 Desember 2000",
        "geolokasi": "4.914°N 96.329°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Peuet-Sagoe.jpg"
    },
    {
        "id": "3",
        "nama": "Geureudong",
        "bentuk": "Stratovulkan",
        "tinggi": "2885 meter",
        "letusan_terakhir": "1937",
        "geolokasi": "4.813°N 96.82°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/geureudong.jpg"
    },
    {
        "id": "4",
        "nama": "Sibayak",
        "bentuk": "Stratovulkan",
        "tinggi": "2212 meter",
        "letusan_terakhir": "1881",
        "geolokasi": "3.23°N 98.52°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sibayak.jpg"
    },
    {
        "id": "5",
        "nama": "Sinabung",
        "bentuk": "Stratovulkan",
        "tinggi": "2460 meter",
        "letusan_terakhir": "2 Maret 2021",
        "geolokasi": "3.17°N 98.392°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sinabung.jpg"
    },
    {
        "id": "6",
        "nama": "Gunung Toba",
        "bentuk": "Supervulkan",
        "tinggi": "2157 meter",
        "letusan_terakhir": "72000 SM",
        "geolokasi": "2.58°N 98.83°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Gunung-Toba.jpg"
    },
    {
        "id": "7",
        "nama": "Sibualbuali",
        "bentuk": "stratovulkan",
        "tinggi": "1819 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "1.556°N 99.255°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sibualbuali.jpg"
    },
    {
        "id": "8",
        "nama": "Lubukraya",
        "bentuk": "stratovulkan",
        "tinggi": "1862 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "1.478°N 99.209°E",
        "status": "Tidak Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Lubukraya.jpg"
    },
    {
        "id": "9",
        "nama": "Sorikmarapi",
        "bentuk": "stratovulkan",
        "tinggi": "2145 meter",
        "letusan_terakhir": "1986",
        "geolokasi": "0.686°N 99.539°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sorikmarapi.jpg"
    },
    {
        "id": "10",
        "nama": "Talakmau",
        "bentuk": "Kompleks",
        "tinggi": "2919 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "0.079°N 99.98°E",
        "status": "Tidak Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Talakmau.jpg"
    },
    {
        "id": "11",
        "nama": "Marapi",
        "bentuk": "Kompleks",
        "tinggi": "2891 meter",
        "letusan_terakhir": "6 Juli 2017",
        "geolokasi": "0.381°S 100.473°E",
        "status": "Aktif",
        "keamanan": "Aman Tapi Tidak Sampai Puncak",
        "gambar": "https://foto-gunung.vercel.app/src/image/Marapi.jpg"
    },
    {
        "id": "12",
        "nama": "Singgalang",
        "bentuk": "Stratovulkan",
        "tinggi": "2877 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "0.420°S 100.317°E",
        "status": "Tidak Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Singgalang.jpg"
    },
    {
        "id": "13",
        "nama": "Tandikat",
        "bentuk": "stratovulkan",
        "tinggi": "2438 meter",
        "letusan_terakhir": "1924",
        "geolokasi": "0.433°S 100.317°E",
        "status": "Aktif",
        "keamanan": "Jarang Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Tandikat.jpg"
    },
    {
        "id": "14",
        "nama": "Sago",
        "bentuk": "Stratovulkan",
        "tinggi": "2271 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "0.354°S 100.378°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sago.jpg"
    },
    {
        "id": "15",
        "nama": "Talang",
        "bentuk": "stratovulkan",
        "tinggi": "2597 meter",
        "letusan_terakhir": "12 April 2005",
        "geolokasi": "0.978°S 100.679°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Talang.jpg"
    },
    {
        "id": "16",
        "nama": "Kerinci",
        "bentuk": "stratovulkan",
        "tinggi": "3800 meter",
        "letusan_terakhir": "17 Oktober 2020",
        "geolokasi": "1.697°S 101.264°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Kerinci.jpg"
    },
    {
        "id": "17",
        "nama": "Sumbing",
        "bentuk": "stratovulkan",
        "tinggi": "2507 meter",
        "letusan_terakhir": "23 Mei 1921",
        "geolokasi": "2.414°S 101.728°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Sumbing.jpg"
    },
    {
        "id": "18",
        "nama": "Bukit Daun",
        "bentuk": "stratovulkan",
        "tinggi": "2467 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "3.38°S 102.37°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Bukit-Daun.jpg"
    },
    {
        "id": "19",
        "nama": "Kaba",
        "bentuk": "stratovulkan",
        "tinggi": "1952 meter",
        "letusan_terakhir": "22 Agustus 2000",
        "geolokasi": "3.52°S 102.62°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Kaba.jpg"
    },
    {
        "id": "20",
        "nama": "Dempo",
        "bentuk": "stratovulkan",
        "tinggi": "3173 meter",
        "letusan_terakhir": "1 Januari 2009",
        "geolokasi": "4.03°S 103.13°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Dempo.jpg"
    },
    {
        "id": "21",
        "nama": "Patah",
        "bentuk": "stratovulkan",
        "tinggi": "2852 meter",
        "letusan_terakhir": "N/A",
        "geolokasi": "4.27°S 103.30°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Patah.jpg"
    },
    {
        "id": "22",
        "nama": "Rajabasa",
        "bentuk": "stratovulkan",
        "tinggi": "1281 meter",
        "letusan_terakhir": "1798",
        "geolokasi": "5.78°S 105.625°E",
        "status": "Tidak Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Rajabasa.jpg"
    },
    {
        "id": "23",
        "nama": "Krakatau",
        "bentuk": "kaldera",
        "tinggi": "813 meter",
        "letusan_terakhir": "22 Desember 2018",
        "geolokasi": "6.102°S 105.423°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Krakatau.jpg"
    },
    {
        "id": "23",
        "nama": "Pulosari",
        "bentuk": "kaldera",
        "tinggi": "813 meter",
        "letusan_terakhir": "22 Desember 2018",
        "geolokasi": "6.102°S 105.423°E",
        "status": "Aktif",
        "keamanan": "Aman Untuk Pendakian",
        "gambar": "https://foto-gunung.vercel.app/src/image/Krakatau.jpg"
    },
];
 
module.exports = gunung;